zad 3.4.5 - v:2
malvor/parking-sample pull request #3
Opened 2023-01-26 08:05 UTC by Dannkru

Hej Jakub!
Problemy dalej mimo Twoich wskazówek:
AbstractParking::getPrice(),
City::getTotalParkingCapacities
pytanie: 
Index -> new Bike Parking
 (nie dałem rady tego ogarnąć. Może w całości jest nie tak zrobione, jak trzeba. Jeśli możesz poproszę jeszcze raz o porady)
Reszta testowana - działa.

2023-01-26 11:42 UTC, malvor commented on index.php
> +
?

2023-01-26 11:42 UTC, malvor commented on index.php
> -$rzeszow = new Model\City('Rzeszów', 'Polska', 210000, 36.9);
Brakuje endofline na końcu pliku. Podsyłałem Ci kiedyś jak to dodać z automatu

2023-01-26 11:42 UTC, malvor commented on src/Model/AbstractParking.php
> +    public function __construct(Money $pricePerHour, int $numberOfPlaces, int $freePlaces)
Free places nie powinno być przesyłane. Bo co jeśli zrobić new Parking(new Money(5, 'PLN'), 20, 40) ?
Będę miał więcej free places niż może pomieścić parking

2023-01-26 11:42 UTC, malvor commented on src/Model/AbstractParking.php
> +        if (!$this->hasFreePlaces($vehicle)) {
Brakuje wywołania "canPark"

2023-01-26 11:42 UTC, malvor commented on src/Model/AbstractParking.php
> +        return new Money(1);
Jeśli jest todo, to nie mam co sprawdzać w tym przypadku. Do poprawy

2023-01-26 11:42 UTC, malvor commented on src/Model/AbstractParking.php
> +        return $total;
Nie bardzo rozumiem ten zapis.

nie łatwiej zrobić po prostu return $this->freePlaces > 0;?

2023-01-26 11:42 UTC, malvor commented on src/Model/BikeParking.php
> +        return $result;
Nie musisz przypisywać tego do zmiennej. Nie potrzebujesz także `??` Zwykłe return $vehicle instanceof Bike

2023-01-26 11:42 UTC, malvor commented on src/Model/BusParking.php
> +        return $result;
j.w.

2023-01-26 11:42 UTC, malvor commented on src/Model/CarParking.php
> +            return $result;
Warunek bardzo nieczytelny. Dodatkowo `??`

Rozbij to używając podejścia Fail Fast

2023-01-26 11:42 UTC, malvor commented on src/Model/City.php
> +		unset($this->parkings[$key]);
wcięćia!

2023-01-26 11:42 UTC, malvor commented on src/Model/City.php
> +		return count($this->parkings);
wcięcia!

2023-01-26 11:42 UTC, malvor commented on src/Model/City.php
> +		// TO DO
No to todo!

2023-01-26 11:42 UTC, malvor commented on src/Model/TaxiParking.php
> +            return $result;
Jak we wcześniejszych przypadkach

2023-01-26 11:42 UTC, malvor commented on src/ValueObject/Money.php
> +        $this->amount   = $amount;
spacja po amount

2023-01-26 11:42 UTC, malvor commented on src/ValueObject/Money.php
> +        return new Money($total);
Money przyjmuje 2 argumenty, nie jeden

2023-02-01 13:59 UTC, malvor requested changes

2023-02-01 13:59 UTC, malvor commented on src/ValueObject/Money.php
> +        return new Money($total);
Money przyjmuje 2 argumenty

2023-02-01 13:59 UTC, malvor commented on src/Model/AbstractParking.php
> +    public function park(VehicleInterface $vehicle): bool
Park  nie powinno nic zwracać

2023-02-01 13:59 UTC, malvor commented on src/Model/AbstractParking.php
> +            return false;
Podobnie jak w przypadku hasFreePlaces tutaj powinien być wrzucany wyjątek

2023-02-01 13:59 UTC, malvor commented on src/Model/AbstractParking.php
> +        return $this->freePlaces--;
Co to?

2023-02-01 13:59 UTC, malvor commented on src/Model/AbstractParking.php
> +        return ($this->freePlaces > 0)? true : false;
Po co to true/false?

2023-02-01 13:59 UTC, malvor commented on src/ValueObject/Money.php
> +        return new Money($total);
Nadal nie widzę zmiany tutaj

2023-02-01 14:01 UTC, malvor commented on src/Model/AbstractParking.php
> +    public function park(VehicleInterface $vehicle): bool
Tu ma być void

2023-02-01 16:36 UTC, Dannkru commented on src/Model/AbstractParking.php
> +            return false;
Myślałem o tym, mogłem dopytać.

2023-02-01 16:36 UTC, Dannkru commented on src/Model/AbstractParking.php
> +        return ($this->freePlaces > 0)? true : false;
ok, kurde jasne

2023-02-03 09:09 UTC, malvor approved these changes

2023-02-03 12:16 UTC, closed without merging